### ISSUE TITLE
Doesn't support Kernel4.X?

### ISSUE THREAD

**Issue by Zhaojp-Frank** [pakmarkthub/dragon#1]
Hi,
interesting work! well done.
A question, from current install guild, it's said "incompatible with kernel 4.x", so may I know what blocks it to support kernel 4.X ? can be resolved? or in plan ?

thanks.

Frank.

**Comment by pakmarkthub** [comment]
Thank you Frank. 

DRAGON currently supports only kernel 3.x since it uses some kernel data structures and functions that are not available on the later kernels. Those data structures and functions are mostly related to file and page cache management. 

We found almost all equivalent functions on kernel 4.x but still need to reimplement and test DRAGON. We plan to direct our effort for developing support for kernel 4.x after we release DRAGON for CUDA10.
