### ISSUE TITLE
Question about deploying Dragon

### ISSUE THREAD

**Issue by weirang** [pakmarkthub/dragon#2]
Hi Dr. Pak Markthub,

Hope this email finds you well. This is Wei Rang, a CS Ph.D. student from UNC Charlotte.

Recently I am trying to reproduce your work in DRAGON: Breaking GPU Memory Capacity Limits with Direct NVM Access.

The followings are my hardware and software specifications:
Memory: 16GB 2x8GB DDR4 2666MHz RDIMM ECC Memory
Processor: Intel Xeon Bronze 3104 1.7GHz * 6
Graphics: Quadro RTX 4000 (11 GB)

OS: CentOS7 Kernel 3.10.0-1062.4.3.el7.x86_64
GPU Driver: NVIDIA-Linux-x86_64-440.36
CUDA: cuda_9.0.176_384.81_linux

When I was trying to replace the original Nvidia GPU driver following your tutorial in Github. A lot of errors occurred and then I tried to modify the patch but it didn't work.

Could you please provide any suggestions on how to deploy and use DRAGON framework? Or should I use the exact same hardware and software configuration as your paper mentioned?

Thank you very much and looking forward to hearing from you.

**Comment by pakmarkthub** [comment]
Hi Wei Rang (@weirang),

Thank  you for your interest in DRAGON. 

Currently, DRAGON supports NVIDIA GPU version 384.81 and 410.48 only. The driver version 440.36 is very new and NVIDIA seems to significantly improve the driver. It would require substantial engineering effort in order to make DRAGON compatible with the current GPU driver version.

For the hardware, you should be able to use your GPU as long as the GPU driver supports it. You may also need a high-performance SSD to gain all of DRAGON's benefits.

**Comment by weirang** [comment]
Thanks for your reply. I have one more question. After checking supported products of Version 384.81, I found Nvidia M40's price falls into our budget. But in the instructions from Github, DRAGON requires an NVIDIA Pascal P100 GPU or above that supports GPU hardware page-fault. So could you please tell me if M40 works well with DRAGON? The price of an Nvidia P100 is really too high to us. Thanks again and looking forward to your reply.

**Comment by pakmarkthub** [comment]
Hi @weirang,

Unfortunately, Maxwell would not work with DRAGON. This is because it lacks the hardware page-faulting support. That component has been introduced since the Pascal architecture. So, any GPUs from the Pascal era (Volta and Turing for example) should be fine.

DISCLAIMER: I have never tested DRAGON with P100 and G100 only. Although it should work even with the gaming cards (GTX, RTX, etc.), I cannot guarantee the support for you.

**Comment by weirang** [comment]
Got it, thanks for your help. Really appreciate that.

**Comment by pakmarkthub** [comment]
Hi @weirang,

I am closing this issue. Please feel free to reopen or create a new one if you need further assistance.

**Comment by weirang** [comment]
Got it. Thank you so much.
